require('core.options')
require('core.keymaps')
require('core.plugins')
require('core.plugin_config.nvim-tree')
require('core.plugin_config.gruvbox')
require('core.plugin_config.lualine')
require('core.plugin_config.treesitter')
require('core.plugin_config.lspconfig')
